name: test

on: [push, pull_request]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        perl: [ '5.34', '5.32', '5.30' ]
    name: Perl ${{ matrix.perl }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
        env: 
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - run: cpanm --quiet --notest --skip-satisfied Module::Build Devel::Cover Devel::Cover::Report::Codecov Devel::Cover::Report::Codecovbash
      - run: cpanm --quiet --notest --skip-satisfied --installdeps --with-recommend .
      - run: perl -V
      - run: cpanm --installdeps .
      - run: perl Build.PL
      - run: ./Build build
      - run: cover -test -report codecov
